=== kessas-youssef/xml-xpath-xquery-parser-in-react/public/Livraison.dtd
<!ELEMENT Livraison (Produits,Commande+,Perssone,Bon-Livraison+)>
<!ELEMENT Produits (Produit+)>
<!ELEMENT Produit (#PCDATA)>
<!ATTLIST Produit Nom-Produit   CDATA #REQUIRED
				  id-Produit    ID #REQUIRED
				  Qte-Stocke    CDATA #REQUIRED
				  Prix-Produit  CDATA #REQUIRED >

<!ELEMENT Commande (Destinataire,Produits-Achete,DateDeCommande,Prix-Total)>
<!ATTLIST Commande id-Commande ID  #REQUIRED >
  

<!ELEMENT Destinataire (Nom,Prenom,Tel,Pays,Wilaya,Address,Poste,Zip?)>
<!ATTLIST Destinataire   id-Client   ID #REQUIRED>
<!ELEMENT Nom (#PCDATA)>
<!ELEMENT Prenom (#PCDATA)>
<!ELEMENT Tel (#PCDATA)>
<!ELEMENT Pays (#PCDATA)>
<!ELEMENT Wilaya (#PCDATA)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT Poste (#PCDATA)>
<!ELEMENT Zip (#PCDATA)>

<!ELEMENT Produits-Achete (Quantite-Achete+)> 
<!ELEMENT Quantite-Achete (#PCDATA)>
<!ATTLIST Quantite-Achete id-Produit IDREF #REQUIRED
                          Nom-Produit CDATA #IMPLIED>


<!ELEMENT DateDeCommande (#PCDATA)>
<!ELEMENT Prix-Total (#PCDATA)>

<!ELEMENT Perssone (equipage,Clients+)>

<!ELEMENT equipage (Gerant,Livreurs)>
<!ELEMENT Gerant (Nom)>


<!ELEMENT Livreurs (Ancien-Livreur+,Nouveau-Livreur+)>

<!ELEMENT Ancien-Livreur (Nom,Prenom,Vehicule,Salaire)>
<!ATTLIST Ancien-Livreur id-livreur  ID #REQUIRED>

<!ELEMENT Nouveau-Livreur (Nom,Prenom,Vehicule,Salaire)>
<!ATTLIST Nouveau-Livreur id-livreur  ID #REQUIRED>

<!ELEMENT Salaire (#PCDATA)>
<!ELEMENT Vehicule (#PCDATA)>

<!ELEMENT Clients (Client+)>
<!ELEMENT Client (Nom,Prenom,Tel,Pays,Wilaya,Address)>
<!ATTLIST Client id-Client  IDREF #REQUIRED>

<!ELEMENT Bon-Livraison (Payage)>
<!ATTLIST Bon-Livraison id-Client  IDREF #REQUIRED
						NomClient  CDATA #REQUIRED
						PrenomClient  CDATA #IMPLIED>

<!ELEMENT Payage (#PCDATA)>
<!ATTLIST Payage type  ( Eddahabia | Main-A-Main )  "Eddahabia" >

=== kessas-youssef/xml-xpath-xquery-parser-in-react/public/Livraison.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Livraison SYSTEM "Livraison.dtd"> 

<?xml-model href="Livraison.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>

<Livraison>

  <!-- Les noms des produits offertes Par l'agence de Livraison -->
  <Produits>

    <Produit Nom-Produit="Souris LOGITECH" id-Produit="P1" Qte-Stocke="25" Prix-Produit="3900" />
    <Produit Nom-Produit="Clavier AORUS" id-Produit="P2" Qte-Stocke="20" Prix-Produit="8000" />
    <Produit Nom-Produit="Casque Logitech" id-Produit="P3" Qte-Stocke="60" Prix-Produit="5000" />
    <Produit Nom-Produit="Carte Mere B200" id-Produit="P4" Qte-Stocke="39" Prix-Produit="20000" />
    <Produit Nom-Produit="Carte Graphique NVIDIA RTX 3080" id-Produit="P5" Qte-Stocke="53" Prix-Produit="400000" />
    <Produit Nom-Produit="Processeur AMD Ryzen 3200g" id-Produit="P6" Qte-Stocke="25" Prix-Produit="25000" />
    <Produit Nom-Produit="Disque dur SSD 500 GO " id-Produit="P7" Qte-Stocke="28" Prix-Produit="16000" />
    <Produit Nom-Produit="RAM DDR4 8GO" id-Produit="P8" Qte-Stocke="30" Prix-Produit="12000" />

  </Produits>
  
  <!--La Commande du client avec ces informations perssonels + les produits achetes-->
  <Commande id-Commande="COM1">


    <Destinataire id-Client="C1">
      <Nom>Merouane</Nom>
      <Prenom>Bendahmane</Prenom>
      <Tel>0543827171</Tel>
      <Pays>ALGERIE</Pays>
      <Wilaya>ORAN</Wilaya>
      <Address> 02 rue aek Belarbi bir el djir</Address>
      <Poste> BIR-EL-DJIR Cdt GUERRAB Med</Poste>
      <Zip>31001</Zip>
    </Destinataire>

    <Produits-Achete>

      <Quantite-Achete id-Produit="P1" Nom-Produit="Souris Logitech">2</Quantite-Achete>
      <Quantite-Achete id-Produit="P6">1</Quantite-Achete>
      <Quantite-Achete id-Produit="P7">3</Quantite-Achete>
      <Quantite-Achete id-Produit="P5">1</Quantite-Achete>

    </Produits-Achete>

    <DateDeCommande>
	              09-01-22
    </DateDeCommande>

    <Prix-Total>480800 </Prix-Total>

  </Commande>

  <Commande id-Commande="COM2">

    <Destinataire id-Client="C2">
      <Nom>Benchouk</Nom>
      <Prenom>Karim</Prenom>
      <Tel>0743828372</Tel>
      <Pays>ALGERIE</Pays>
      <Wilaya>ALGER</Wilaya>
      <Address> 04 rue ahmed benbella akid lotfi</Address>
      <Poste> ORAN-RP</Poste>

    </Destinataire>

    <Produits-Achete>

      <Quantite-Achete id-Produit="P2">1</Quantite-Achete>
      <Quantite-Achete id-Produit="P8">2</Quantite-Achete>
      <Quantite-Achete id-Produit="P4" Nom-Produit="Carte Mere B200">3</Quantite-Achete>

    </Produits-Achete>

    <DateDeCommande>
                  01-02-23
    </DateDeCommande>

    <Prix-Total>40000 </Prix-Total>
     

  </Commande>

  <!-- Informations sur Le staff de l'agence de Livraison + les clients -->
  <Perssone>
    <equipage>
      <Gerant>
        <Nom> Moussa ahmed </Nom>
      </Gerant>

      <Livreurs>
        <Ancien-Livreur id-livreur="L1">
          <Nom>Youcef</Nom>
          <Prenom>Kessas</Prenom>
          <Vehicule> Fourgon Hyundai H350</Vehicule>
          <Salaire>35000</Salaire>

        </Ancien-Livreur>

        <Nouveau-Livreur id-livreur="L2">
          <Nom>Chreief</Nom>
          <Prenom>Mohamemd</Prenom>
          <Vehicule> Renault Kangoo</Vehicule>
          <Salaire>25000</Salaire>

        </Nouveau-Livreur>
      </Livreurs>


    </equipage>

    <Clients>
      <Client id-Client="C1">
        <Nom>Merouane</Nom>
        <Prenom>Bendahmane</Prenom>
        <Tel>0543827171</Tel>
        <Pays>Dz</Pays>
        <Wilaya>Oran</Wilaya>
        <Address> 02 rue</Address>
      </Client>

      <Client id-Client="C2">
        <Nom>Benchouk</Nom>
        <Prenom>Karim</Prenom>
        <Tel>0743828372</Tel>
        <Pays>Dz</Pays>
        <Wilaya>Oran</Wilaya>
        <Address> 01 rue</Address>
      </Client>
    </Clients>

  </Perssone>

  <!--Le bon de livraison pour le client et indication du type de payage-->
  <Bon-Livraison id-Client="C1" NomClient="Merouane" PrenomClient="Bendahmane">
    <Payage type="Eddahabia" />


  </Bon-Livraison>

  <Bon-Livraison id-Client="C2" NomClient="Benchouk">
    <Payage type="Main-A-Main" />


  </Bon-Livraison>

</Livraison>
